---
  apiVersion: integrations.flux/v1
  kind: FluxHelmResource
  metadata:
    name: mariadb
    namespace: kube-system
    labels:
      chart: mariadb
  spec:
    chartgitpath: mariadb
    customizations:
      - name: image
        value: bitnami/mariadb:10.1.30-r1

