---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmResource
  metadata:
    name: mongodb
    namespace: kube-system
    labels:
      chart: mongodb
  spec:
    chartgitpath: mongodb
    releasename: kube-system-mongodb
    customizations:
      - name: image
        value: bitnami/mongodb:3.7.1-r1
      - name: imagePullPolicy
        value: IfNotPresent
            
