---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmRelease
  metadata:
    name: mysql1
    namespace: kube-system
    labels:
      chart: mysql
  spec:
    chartGitPath: mysql
    releaseName: kube-system-mysql
    values:
      - name: imageTag
        value: 5.7.14
